[package]
name = "vm"
version = "0.1.0"
authors = []

[dependencies]
heck = "0.3.0"
sha3 = "0.7.3"
redis = "0.9.0"
rustler = { git = "https://github.com/hansihe/rustler.git"}
time = "*"
lazy_static = "0.2"
wasmi = "0.4.2"
serde = "1.0.85"
serde_derive = "1.0.85"
serde_bytes = "0.10.4"
serde_cbor = "0.9.0"
hex = "*"
