[package]
name = "vm"
version = "0.1.0"
authors = []

[dependencies]
heck = "0.3.0"
sha3 = "0.7.3"
redis = "0.8.0"
rustler = { git = "https://github.com/hansihe/rustler.git"}
time = "*"
lazy_static = "0.2"
wasmi = { path = "../../../wasmi" }
serde_cbor = { path = "../../../cbor" }
