[package]
name = "vm_nif"
version = "0.1.0"
authors = []

[lib]
name = "vm_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
redis = "0.8.0"
serde_cbor = { path = "../../../cbor" }
vm = { "path" = "../vm" }
rustler = "0.18.0"
rustler_codegen = "0.18.0"
lazy_static = "1.0"
